from typing import List, Optional
from pydantic import BaseModel, Field


# --- Previous Schemas ---
class AlertExplanationRequest(BaseModel):
    username: str
    anomaly_score: float
    mitre_techniques: List[str] = Field(default_factory=list)
    flagged_reasons: List[str] = Field(...)
    raw_events_summary: str = Field(...)


class AlertExplanationResponse(BaseModel):
    summary: str
    suspected_tactics: List[str]
    confidence_score: str
    remediation_steps: List[str]


# --- New Feature 1 Schemas (AI Incident Investigator) ---
class IncidentInvestigationRequest(BaseModel):
    incident_id: str = Field(..., description="Target incident ID from the correlation engine")


class IncidentInvestigationReport(BaseModel):
    incident_id: str
    executive_summary: str = Field(..., description="High-level narrative explaining the security event")
    incident_timeline_analysis: List[str] = Field(..., description="Chronological timeline analysis of the attack path")
    mitre_attack_mapping: List[str] = Field(..., description="Mapping of observed behaviors to MITRE ATT&CK tactics")
    containment_recommendations: List[str] = Field(..., description="Immediate steps to isolate and mitigate the threat")


# --- New Feature 2 Schemas (Natural Language Query) ---
class NaturalLanguageQueryRequest(BaseModel):
    query: str = Field(..., description="e.g. 'Why is Alice high risk?' or 'Show suspicious file transfers.'")


class NaturalLanguageQueryResponse(BaseModel):
    query: str
    answer: str = Field(..., description="The response generated by the AI based on the system state")
    referenced_entities: List[str] = Field(default_factory=list, description="Users, devices, or resources mentioned")